language: node_js
node_js: 8

sudo: required
dist: trusty

cache:
  directories:
    - node_modules

os:
  - osx
  - linux

addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      - xz-utils
      - rpm
      - bsdtar
      - gcc-multilib
      - g++-multilib


install:
  - curl -L https://yarnpkg.com/latest.tar.gz | tar xvz && mv yarn-* $HOME/.yarn
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn
  - yarn test

script:
  - yarn dist

notifications:
  slack: ramme:44ubE4BVf3FGi8OldEKL743J
  email: false
